// Copyright 2021 Arnie Weber (@310weber)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Unique code generated by "python util/vial_generate_keyboard_uid.py"
#define VIAL_KEYBOARD_UID {0xDD, 0xB2, 0xEA, 0xB2, 0x18, 0x55, 0x99, 0xD1}

/* Set key combo to unlock in VIAL
   Also remove "VIAL_INSECURE = yes" from rules.mk */
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }     // sets unlock to ESC + ENTER
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }

/* Options to save memory */
#define VIAL_TAP_DANCE_ENTRIES 1
#define VIAL_COMBO_ENTRIES 1

#ifndef NO_DEBUG
#define NO_DEBUG
#endif  // !NO_DEBUG

#ifndef NO_PRINT
#define NO_PRINT
#endif  // !NO_PRINT
