// Copyright 2021 Arnie Weber (@310weber)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Unique code generated by "python util/vial_generate_keyboard_uid.py"
#define VIAL_KEYBOARD_UID {0xE7, 0xE7, 0x66, 0x01, 0x19, 0x10, 0xCA, 0x35}

/* Set key combo to unlock in VIAL
   Also remove "VIAL_INSECURE = yes" from rules.mk */
#define VIAL_UNLOCK_COMBO_ROWS { 0, 16 }     // sets unlock to ESC + ENTER
#define VIAL_UNLOCK_COMBO_COLS { 0, 17 }

/* Options to save memory */
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4

#ifndef NO_DEBUG
#define NO_DEBUG
#endif  // !NO_DEBUG

#ifndef NO_PRINT
#define NO_PRINT
#endif  // !NO_PRINT
