// Copyright 2021 Arnie Weber (@310weber)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

// Unique code generated by "python util/vial_generate_keyboard_uid.py"
#define VIAL_KEYBOARD_UID {0x66, 0x67, 0x88, 0x77, 0x8B, 0xB5, 0x52, 0x78}

/* Set key combo to unlock in VIAL
   Also remove "VIAL_INSECURE = yes" from rules.mk */
#define VIAL_UNLOCK_COMBO_ROWS { 0, 7 }     // sets unlock to ESC + ENTER
#define VIAL_UNLOCK_COMBO_COLS { 0, 6 }

/* Options to save memory */
#define DYNAMIC_KEYMAP_LAYER_COUNT 5        // Match to number of layers if > 4
#define VIAL_TAP_DANCE_ENTRIES 6
#define VIAL_COMBO_ENTRIES 6

#ifndef NO_DEBUG
#define NO_DEBUG
#endif  // !NO_DEBUG

#ifndef NO_PRINT
#define NO_PRINT
#endif  // !NO_PRINT
